name: Build

#on:
#  workflow_dispatch

on:
  push:
    branches:
      - main

jobs:
  SmokeTests:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        config: [Debug, Release]
        include:
          - os: macos-14
            name: macOS
          - os: ubuntu-22.04
            name: Linux
          - os: windows-2022
            name: Windows
    env:
        VCPKG_ROOT: "${{ github.workspace }}/../vcpkg"

    steps:

      - name: Path (Windows)
        if: runner.os == 'Windows'
        run: |
           echo "${{ github.workspace }}\..\vcpkg\installed\x64-windows\bin"
           echo "${{ github.workspace }}\..\vcpkg\installed\x64-windows\bin" >> "$env:GITHUB_PATH"

      - name: TestPath (Windows)
        if: runner.os == 'Windows'
        run: |
           echo "$env:PATH"
           echo "$env:VCPKG_ROOT"

      - name: Prerequisites (macOS)
        if: runner.os == 'macOS'
        run: |
           brew install pkgconf

      - name: Prerequisites (Windows)
        if: runner.os == 'Windows'
        run: |
           cd ..
           git clone https://github.com/Microsoft/vcpkg --depth=1
           cd vcpkg; cmd /c bootstrap-vcpkg.bat
           vcpkg install pkgconf
           vcpkg install gmp

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: |
           pwd
           cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DMINI_GMP_PLUS_WITH_TESTS=1

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Display built (Windows)
        if: runner.os == 'Windows'
        run: |
           tree /f

      - name: Test
        run: |
            echo $PATH
            cd build/tests; ctest -C ${{ matrix.config }}
